# Containers
services:
  pmsystem:
    build: .
    ports:
      - "8080:8080"
    networks:
      - net
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PmSystem;User Id=sa;Password=pass123;TrustServerCertificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - net
    hostname: sqlserver
    volumes:
      - sql_data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pass123

# Network
networks:
  net:

# Volumes
volumes:
  sql_data:
